[tools]
maven = "latest"
dotnet = "latest"

[tasks]
build_and_test = "mvn --quiet -B verify --file pom.xml"
format = "mvn --quiet formatter:format"

[settings]
# we put the java version in the .java-version file instead of here so that it's easy to override in the CI matrix
idiomatic_version_file_enable_tools = ["java"]
